import { describe, expect, it } from "vitest";
import {
  CURRENT_APP_EXPORTS,
  PUBLIC_REPORT_CATALOG,
  REPORT_LIBRARY_UNAVAILABLE_DOCUMENTS,
  buildReportAccessPlan,
} from "../src/main/amazon/report-library";

const US = "ATVPDKIKX0DER";

const OFFICIAL_REPORT_TYPES = new Set(`
FEE_DISCOUNTS_REPORT
GET_BRAND_ANALYTICS_SEARCH_CATALOG_PERFORMANCE_REPORT
GET_BRAND_ANALYTICS_SEARCH_QUERY_PERFORMANCE_REPORT
GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT
GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT
GET_BRAND_ANALYTICS_REPEAT_PURCHASE_REPORT
GET_VENDOR_REAL_TIME_INVENTORY_REPORT
GET_VENDOR_REAL_TIME_TRAFFIC_REPORT
GET_VENDOR_REAL_TIME_SALES_REPORT
GET_VENDOR_SALES_REPORT
GET_VENDOR_NET_PURE_PRODUCT_MARGIN_REPORT
GET_VENDOR_TRAFFIC_REPORT
GET_VENDOR_FORECASTING_REPORT
GET_VENDOR_INVENTORY_REPORT
GET_SALES_AND_TRAFFIC_REPORT
GET_B2B_PRODUCT_OPPORTUNITIES_RECOMMENDED_FOR_YOU
GET_B2B_PRODUCT_OPPORTUNITIES_NOT_YET_ON_AMAZON
GET_XML_BROWSE_TREE_DATA
GET_EASYSHIP_DOCUMENTS
GET_EASYSHIP_PICKEDUP
GET_EASYSHIP_WAITING_FOR_PICKUP
GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL
GET_AMAZON_FULFILLED_SHIPMENTS_DATA_INVOICING
GET_AMAZON_FULFILLED_SHIPMENTS_DATA_TAX
GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL
GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL
GET_XML_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL
GET_XML_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL
GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_SALES_DATA
GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_PROMOTION_DATA
GET_FBA_FULFILLMENT_CUSTOMER_TAXES_DATA
GET_REMOTE_FULFILLMENT_ELIGIBILITY
GET_AFN_INVENTORY_DATA
GET_AFN_INVENTORY_DATA_BY_COUNTRY
GET_LEDGER_SUMMARY_VIEW_DATA
GET_LEDGER_DETAIL_VIEW_DATA
GET_RESERVED_INVENTORY_DATA
GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA
GET_FBA_MYI_ALL_INVENTORY_DATA
GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT
GET_FBA_FULFILLMENT_INBOUND_NONCOMPLIANCE_DATA
GET_STRANDED_INVENTORY_UI_DATA
GET_STRANDED_INVENTORY_LOADER_DATA
GET_FBA_STORAGE_FEE_CHARGES_DATA
GET_FBA_INVENTORY_PLANNING_DATA
GET_FBA_OVERAGE_FEE_CHARGES_DATA
GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA
GET_FBA_REIMBURSEMENTS_DATA
GET_FBA_FULFILLMENT_LONGTERM_STORAGE_FEE_CHARGES_DATA
GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA
GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_REPLACEMENT_DATA
GET_FBA_RECOMMENDED_REMOVAL_DATA
GET_FBA_FULFILLMENT_REMOVAL_ORDER_DETAIL_DATA
GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA
GET_FLAT_FILE_OPEN_LISTINGS_DATA
GET_MERCHANT_LISTINGS_ALL_DATA
GET_MERCHANT_LISTINGS_DATA
GET_MERCHANT_LISTINGS_INACTIVE_DATA
GET_MERCHANT_LISTINGS_DATA_BACK_COMPAT
GET_MERCHANT_LISTINGS_DATA_LITE
GET_MERCHANT_LISTINGS_DATA_LITER
GET_MERCHANT_CANCELLED_LISTINGS_DATA
GET_MERCHANTS_LISTINGS_FYP_REPORT
GET_PAN_EU_OFFER_STATUS
GET_MFN_PANEU_OFFER_STATUS
GET_REFERRAL_FEE_PREVIEW_REPORT
GET_FLAT_FILE_VAT_INVOICE_DATA_REPORT
GET_XML_VAT_INVOICE_DATA_REPORT
GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING
GET_ORDER_REPORT_DATA_INVOICING
GET_ORDER_REPORT_DATA_TAX
GET_ORDER_REPORT_DATA_SHIPPING
GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING
GET_FLAT_FILE_ORDER_REPORT_DATA_SHIPPING
GET_FLAT_FILE_ORDER_REPORT_DATA_TAX
GET_FLAT_FILE_ARCHIVED_ORDERS_DATA_BY_ORDER_DATE
GET_FLAT_FILE_PENDING_ORDERS_DATA
GET_PENDING_ORDERS_DATA
GET_CONVERGED_FLAT_FILE_PENDING_ORDERS_DATA
GET_DATE_RANGE_FINANCIAL_HOLDS_DATA
GET_SELLER_FEEDBACK_DATA
GET_V1_SELLER_PERFORMANCE_REPORT
GET_V2_SELLER_PERFORMANCE_REPORT
GET_PROMOTION_PERFORMANCE_REPORT
GET_COUPON_PERFORMANCE_REPORT
END_USER_DATA_REPORT
FBA_BULK_INVOICE
MARKETPLACE_ASIN_PAGE_VIEW_METRICS
GET_EPR_MONTHLY_REPORTS
GET_EPR_QUARTERLY_REPORTS
GET_EPR_ANNUAL_REPORTS
GET_XML_RETURNS_DATA_BY_RETURN_DATE
GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE
GET_XML_MFN_PRIME_RETURNS_REPORT
GET_CSV_MFN_PRIME_RETURNS_REPORT
GET_XML_MFN_SKU_RETURN_ATTRIBUTES_REPORT
GET_FLAT_FILE_MFN_SKU_RETURN_ATTRIBUTES_REPORT
GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE
GET_V2_SETTLEMENT_REPORT_DATA_XML
GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2
GST_MTR_STOCK_TRANSFER_REPORT
GST_MTR_B2B
GST_MTR_B2C
GET_FLAT_FILE_SALES_TAX_DATA
SC_VAT_TAX_REPORT
GET_VAT_TRANSACTION_DATA
GET_GST_MTR_B2B_CUSTOM
GET_GST_MTR_B2C_CUSTOM
GET_GST_STR_ADHOC
`.trim().split(/\s+/u));

describe("public Reports API document library", () => {
  it("tracks all 109 unique report types in the current official table exactly once", () => {
    const actual = PUBLIC_REPORT_CATALOG.map(({ reportType }) => reportType);
    expect(OFFICIAL_REPORT_TYPES.size).toBe(109);
    expect(actual).toHaveLength(109);
    expect(new Set(actual).size).toBe(actual.length);
    expect(new Set(actual)).toEqual(OFFICIAL_REPORT_TYPES);
  });

  it("keeps documented availability separate from this app's downloader", () => {
    const plan = buildReportAccessPlan({
      marketplaceId: US,
      reportType: "GET_AFN_INVENTORY_DATA",
    });
    expect(plan).toEqual({
      reportType: "GET_AFN_INVENTORY_DATA",
      marketplaceId: US,
      state: "READY_TO_PLAN",
      amazonPublicArtifactAvailable: true,
      appDownloadImplemented: false,
      notice: expect.stringMatching(/Amazon.*公開.*尚未接線/u),
      nextStep: expect.stringMatching(/專用 parser/u),
    });
  });

  it("fails closed for mixed fulfillment, RDT, roles, generated and vendor reports", () => {
    expect(buildReportAccessPlan({
      marketplaceId: US,
      reportType: "GET_MERCHANT_LISTINGS_ALL_DATA",
    }).state).toBe("FBA_FILTER_REQUIRED");
    expect(buildReportAccessPlan({
      marketplaceId: US,
      reportType: "GET_AMAZON_FULFILLED_SHIPMENTS_DATA_INVOICING",
    }).state).toBe("RDT_REQUIRED");
    expect(buildReportAccessPlan({
      marketplaceId: US,
      reportType: "GET_SALES_AND_TRAFFIC_REPORT",
    }).state).toBe("EXTRA_ROLE_REQUIRED");
    expect(buildReportAccessPlan({
      marketplaceId: US,
      reportType: "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2",
    }).state).toBe("AMAZON_GENERATED_ONLY");
    expect(buildReportAccessPlan({
      marketplaceId: US,
      reportType: "GET_VENDOR_SALES_REPORT",
    }).state).toBe("VENDOR_ONLY");
  });

  it("marks official store limits and manual prerequisites", () => {
    expect(buildReportAccessPlan({
      marketplaceId: US,
      reportType: "GET_PAN_EU_OFFER_STATUS",
    }).state).toBe("MARKETPLACE_UNAVAILABLE");
    expect(buildReportAccessPlan({
      marketplaceId: US,
      reportType: "GET_FLAT_FILE_SALES_TAX_DATA",
    })).toMatchObject({
      state: "RDT_REQUIRED",
      appDownloadImplemented: false,
    });
    expect(buildReportAccessPlan({
      marketplaceId: US,
      reportType: "GET_DATE_RANGE_FINANCIAL_HOLDS_DATA",
    }).state).toBe("MANUAL_PREREQUISITE");
  });

  it("lists the exports that the app already creates separately", () => {
    expect(CURRENT_APP_EXPORTS.map(({ id }) => id)).toEqual([
      "CONTENT_AUDIT_XLSX",
      "IMAGE_AUDIT_XLSX",
      "AGED_INVENTORY_XLSX",
      "SUBSCRIPTION_AUDIT_XLSX",
      "UNBOUND_VARIATION_AUDIT_XLSX",
      "REVIEW_TOPIC_AUDIT_XLSX",
    ]);
    expect(CURRENT_APP_EXPORTS.at(-1)).toMatchObject({
      availability: "AVAILABLE_AFTER_SUCCESSFUL_AUDIT",
      scope: expect.stringMatching(/評論主題影響值.*星等下降方向的影響值.*不是商品負星等.*不會轉成 0 或絕對值.*不含完整 review/u),
    });
  });

  it("contains no private Seller Central URL, secret fields, or fake review corpus", () => {
    const serialized = JSON.stringify({
      catalog: PUBLIC_REPORT_CATALOG,
      exports: CURRENT_APP_EXPORTS,
      unavailable: REPORT_LIBRARY_UNAVAILABLE_DOCUMENTS,
    });
    expect(serialized).not.toMatch(/sellercentral\.amazon\./iu);
    expect(serialized).not.toMatch(/refresh.?token|client.?secret|seller.?id/iu);
    expect(REPORT_LIBRARY_UNAVAILABLE_DOCUMENTS.find(({ id }) => id === "PRODUCT_REVIEW_TEXT"))
      .toMatchObject({ reason: expect.stringMatching(/不提供完整 review/u) });
  });
});
