import React from "react";
import { act, create, type ReactTestRenderer } from "react-test-renderer";
import { afterEach, describe, expect, it, vi } from "vitest";
import VinePanel from "../src/renderer/src/components/vine-panel";
import type { VineSnapshot } from "../src/shared/vine";
(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;
let renderer: ReactTestRenderer | null = null;
afterEach(async () => { if (renderer) await act(async () => renderer!.unmount()); renderer = null; vi.unstubAllGlobals(); });
const snapshot: VineSnapshot = { schemaVersion: 1, marketplaceId: "ATVPDKIKX0DER", source: "seller-central-manual", storage: "encrypted-local", storageNotice: "本機加密", window: { startDate: "2026-07-14", endDate: "2026-09-11" }, updatedAt: "2026-09-12T01:00:00.000Z", rows: [{ sellerSku: "SKU-ONE", asin: "B000000001", enrollmentDate: "2026-09-10", enrolled: 30, claimed: 15, reviews: 7, importedAt: "2026-09-12T01:00:00.000Z" }, { sellerSku: "SKU-TWO", asin: "B000000002", enrollmentDate: "2026-09-11", enrolled: 2, claimed: null, reviews: 0, importedAt: "2026-09-12T01:00:00.000Z" }] };
describe("Vine progress panel", () => {
  it("shows manual-source progress for 60 days without inventing missing counts or calling sync", async () => {
    const fetch = vi.fn(async () => new Response(JSON.stringify(snapshot)));
    vi.stubGlobal("fetch", fetch);
    await act(async () => { renderer = create(<VinePanel onClose={() => undefined} />); });
    expect(fetch).toHaveBeenCalledExactlyOnceWith("/api/vine", { signal: expect.any(AbortSignal) });
    const text = JSON.stringify(renderer!.toJSON());
    expect(text).toContain("手動匯入");
    expect(text).toContain("近 60 天");
    expect(text).toContain("未回報");
    const bars = renderer!.root.findAllByType("progress");
    expect(bars.some((bar) => bar.props.max === 30 && bar.props.value === 15)).toBe(true);
    expect(bars.some((bar) => bar.props.max === 15 && bar.props.value === 7)).toBe(true);
    expect(bars.some((bar) => bar.props.max === 2 && bar.props.value === 0)).toBe(true);
  });
  it("clears private progress and ignores pending replies when the account context changes", async () => {
    let invalidate!: () => void;
    const unsubscribe = vi.fn();
    vi.stubGlobal("window", { fbaOS: { app: { onContextInvalidated: (listener: () => void) => { invalidate = listener; return unsubscribe; } } } });
    let release!: (response: Response) => void;
    const fetch = vi.fn(async () => new Response(JSON.stringify(snapshot)));
    vi.stubGlobal("fetch", fetch);
    await act(async () => { renderer = create(<VinePanel onClose={() => undefined} />); });
    expect(JSON.stringify(renderer!.toJSON())).toContain("SKU-ONE");
    fetch.mockImplementationOnce(() => new Promise((resolve) => { release = resolve; }));
    const refresh = () => renderer!.root.findAllByType("button").find((button) => button.children.join("") === "重新讀取")!;
    await act(async () => { refresh().props.onClick(); });
    const pendingSignal = (fetch.mock.calls[1] as unknown as [string, { signal: AbortSignal }])[1].signal;
    await act(async () => { invalidate(); });
    expect(pendingSignal.aborted).toBe(true);
    expect(JSON.stringify(renderer!.toJSON())).not.toContain("SKU-ONE");
    expect(fetch).toHaveBeenCalledTimes(2);
    await act(async () => { release(new Response(JSON.stringify(snapshot))); });
    expect(JSON.stringify(renderer!.toJSON())).not.toContain("SKU-ONE");
    expect(JSON.stringify(renderer!.toJSON())).toContain("帳號或安全連線已變更");
    await act(async () => { renderer!.unmount(); });
    renderer = null;
    expect(unsubscribe).toHaveBeenCalledOnce();
  });
  it("imports only after a user action and retains rejected rows for correction", async () => {
    const text = "enrollmentDate,sellerSku,asin,enrolled,claimed,reviews\n2026-09-11,SKU-ONE,B000000001,30,15,7";
    const fetch = vi.fn(async () => new Response(JSON.stringify(snapshot)));
    vi.stubGlobal("fetch", fetch);
    await act(async () => { renderer = create(<VinePanel onClose={() => undefined} />); });
    const input = renderer!.root.findByProps({ "aria-label": "Vine 進度資料" });
    await act(async () => { input.props.onChange({ target: { value: text } }); });
    expect(fetch).toHaveBeenCalledTimes(1);
    fetch.mockResolvedValueOnce(new Response(JSON.stringify({ ...snapshot, storage: "session-only", storageNotice: "此工作階段", importResult: { accepted: 0, rejected: [{ line: 2, message: "未找到 FBA 身分" }] } })));
    await act(async () => { renderer!.root.findAllByType("button").find((button) => button.children.join("") === "核對並匯入")!.props.onClick(); });
    expect(fetch).toHaveBeenLastCalledWith("/api/vine/import", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ text }), signal: expect.any(AbortSignal) });
    expect(input.props.value).toBe(text);
    expect(JSON.stringify(renderer!.toJSON())).toContain("未找到 FBA 身分");
    expect(renderer!.root.findByProps({ className: "vine-storage-warning" }).children).toEqual(["此工作階段"]);
  });
});
