export const CONTENT_SPELLING_DICTIONARY_VERSION =
  "dictionary-en@4.0.0 / nspell@2.1.5";
export const CONTENT_SPELLING_DICTIONARY_LANGUAGE = "SCOWL en_US 2020.12.07";
export const CONTENT_SPELLING_ALLOWLIST_COUNT = 53;
